// import { Inter } from "next/font/google"; // Commented out
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] }); // Commented out

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Replaced with simple body
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}